version: "3.5"
services:
  websockify:
    image: "statusteam/websockify:v0.10.0"
    command:
      - "80"
      - "nwaku.nwaku.dappnode:60000"
  nwaku:
    image: "nwaku.nwaku.dnp.dappnode.eth:0.1.0"
    build:
      context: nwaku
      args:
        UPSTREAM_VERSION: v0.14.0
    ports:
      - "60000:60000/tcp"
      - "60000:60000/udp"
      - "9005:9005/udp"
    environment:
      DNS_DISCOVERY_URL: ""
      LOG_LEVEL: DEBUG
      MAX_CONNECTIONS: 150
      PRIVACY: custom
      WAKUNODE2_AGENT_STRING: nwaku_on_dappnode
      RANDOMIZE_ADDRESS: "true"
      EXPERIMENTAL_FEATURES: "false"
      WAKUNODE2_STORE: "false"
      WAKUNODE2_STORE_MESSAGE_DB_URL: "sqlite:///data/store.sqlite3"
      WAKUNODE2_STORE_MESSAGE_RETENTION_POLICY: "time:2592000"
      WAKUNODE2_FILTER: "false"
      WAKUNODE2_LIGHTPUSH: "false"
      NETWORK: wakuv2.prod
      EXTRA_OPTS: ""
    restart: unless-stopped
    volumes:
      - "nwakudb:/data"
volumes:
  nwakudb: {}
